#!/usr/bin/env bash
# collect_accounts.sh
#
# Run as root on a target host to generate Ansible var files from existing
# accounts. Output matches the format expected by the manage_user role.
#
# Usage:
#   sudo tools/collect_accounts.sh [USERS_OUT] [SVC_OUT]
#
# Defaults (relative to the repo root, resolved from the script's location):
#   USERS_OUT  vars/users.yml
#   SVC_OUT    vars/service_accounts.yml
#
# Override UID ranges via environment:
#   USER_MIN_UID  (default: 1000)  lower bound for regular users
#   USER_MAX_UID  (default: 65533) upper bound — excludes nobody (65534)
#   SVC_MIN_UID   (default: 100)   lower bound for service accounts
#   SVC_MAX_UID   (default: 999)   upper bound for service accounts

set -euo pipefail

SCRIPT="$(basename "$0")"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ---- Configuration -----------------------------------------------------------

USER_MIN_UID="${USER_MIN_UID:-1000}"
USER_MAX_UID="${USER_MAX_UID:-65533}"
SVC_MIN_UID="${SVC_MIN_UID:-100}"
SVC_MAX_UID="${SVC_MAX_UID:-999}"

USERS_OUT="${1:-${REPO_ROOT}/vars/users.yml}"
SVC_OUT="${2:-${REPO_ROOT}/vars/service_accounts.yml}"

DEFAULT_USER_SHELL="/bin/bash"
DEFAULT_SVC_SHELL="/usr/sbin/nologin"
DEFAULT_HOME_BASE="/home"

# ---- Helpers -----------------------------------------------------------------

die()  { echo "$SCRIPT: error: $*" >&2; exit 1; }
info() { echo "$SCRIPT: $*" >&2; }

check_root() {
    [[ $EUID -eq 0 ]] || die "must be run as root"
}

# Wrap a string in YAML double quotes, escaping backslashes and double quotes.
dquote() {
    local s="${1//\\/\\\\}"
    s="${s//\"/\\\"}"
    printf '"%s"' "$s"
}

# Print supplementary group names for a user, one per line.
# Excludes the primary group and any group matching the username.
supp_groups() {
    local user="$1"
    local primary
    primary=$(id -gn "$user" 2>/dev/null) || return 0
    id -nG "$user" 2>/dev/null \
        | tr ' ' '\n' \
        | grep -Ev "^${user}$|^${primary}$" \
        | sort \
        || true
}

# Print the first public key from ~/.ssh/authorized_keys, or nothing.
first_key() {
    local keyfile="$1/.ssh/authorized_keys"
    [[ -f "$keyfile" ]] || return 0
    grep -v '^\s*#' "$keyfile" 2>/dev/null | grep -v '^\s*$' | head -1 || true
}

# Count non-comment lines in authorized_keys.
key_count() {
    local keyfile="$1/.ssh/authorized_keys"
    [[ -f "$keyfile" ]] || { echo 0; return; }
    grep -cv '^\s*#\|^\s*$' "$keyfile" 2>/dev/null || echo 0
}

# Exit 0 if a sudoers drop-in exists for the user.
has_sudo() {
    [[ -f "/etc/sudoers.d/$1" ]]
}

# ---- Entry writers -----------------------------------------------------------

write_user_entry() {
    local name="$1" uid="$2" comment="$3" home="$4" shell="$5"

    echo "  - name: $name"
    echo "    uid: $uid"

    [[ -n "$comment" ]] && echo "    comment: $(dquote "$comment")"

    local key nkeys
    key=$(first_key "$home")
    nkeys=$(key_count "$home")

    if [[ -n "$key" ]]; then
        echo "    ssh_public_key: $(dquote "$key")"
        [[ "$nkeys" -gt 1 ]] && \
            echo "    # WARNING: $nkeys keys in authorized_keys — only the first is captured here"
    else
        echo "    ssh_public_key: \"\"  # no authorized_keys found — add before running playbook"
    fi

    has_sudo "$name" && echo "    sudo: true"

    local groups=()
    while IFS= read -r g; do
        [[ -n "$g" ]] && groups+=("$g")
    done < <(supp_groups "$name")

    if [[ ${#groups[@]} -gt 0 ]]; then
        echo "    groups:"
        for g in "${groups[@]}"; do
            echo "      - $g"
        done
    fi

    # Omit shell and home when they match the role defaults.
    [[ "$shell" != "$DEFAULT_USER_SHELL" ]] && echo "    shell: $shell"
    [[ "$home"  != "$DEFAULT_HOME_BASE/$name" ]] && echo "    home: $home"

    echo
}

write_svc_entry() {
    local name="$1" uid="$2" comment="$3" home="$4" shell="$5"

    echo "  - name: $name"
    echo "    uid: $uid"

    [[ -n "$comment" ]] && echo "    comment: $(dquote "$comment")"

    has_sudo "$name" && echo "    sudo: true"

    local groups=()
    while IFS= read -r g; do
        [[ -n "$g" ]] && groups+=("$g")
    done < <(supp_groups "$name")

    if [[ ${#groups[@]} -gt 0 ]]; then
        echo "    groups:"
        for g in "${groups[@]}"; do
            echo "      - $g"
        done
    fi

    # Omit shell and home when they match the role defaults.
    [[ "$shell" != "$DEFAULT_SVC_SHELL" ]] && echo "    shell: $shell"
    [[ "$home"  != "$DEFAULT_HOME_BASE/$name" ]] && echo "    home: $home"

    echo
}

# ---- Main --------------------------------------------------------------------

check_root

mkdir -p "$(dirname "$USERS_OUT")" "$(dirname "$SVC_OUT")"

user_count=0
svc_count=0

{
    echo "---"
    echo "# Generated by $SCRIPT on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "# Fill in any empty ssh_public_key values before running the playbook."
    echo "manage_user_accounts:"

    while IFS=: read -r name _ uid _ comment home shell; do
        [[ "${uid:-0}" -ge "$USER_MIN_UID" && "${uid:-0}" -le "$USER_MAX_UID" ]] || continue
        write_user_entry "$name" "$uid" "$comment" "$home" "$shell"
        (( ++user_count ))
    done < /etc/passwd

    [[ "$user_count" -eq 0 ]] && echo "  []"
} > "$USERS_OUT"

{
    echo "---"
    echo "# Generated by $SCRIPT on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "# Service accounts with UID ${SVC_MIN_UID}–${SVC_MAX_UID}."
    echo "# Remove any entries that should not be managed by Ansible."
    echo "manage_user_service_accounts:"

    while IFS=: read -r name _ uid _ comment home shell; do
        [[ "${uid:-0}" -ge "$SVC_MIN_UID" && "${uid:-0}" -le "$SVC_MAX_UID" ]] || continue
        write_svc_entry "$name" "$uid" "$comment" "$home" "$shell"
        (( ++svc_count ))
    done < /etc/passwd

    [[ "$svc_count" -eq 0 ]] && echo "  []"
} > "$SVC_OUT"

info "wrote $user_count user(s)           → $USERS_OUT"
info "wrote $svc_count service account(s)  → $SVC_OUT"
info "review output before running the playbook"
