galaxy_info:
  author: TobyAnscombe
  description: Manage user accounts with SSH key authentication on Ubuntu
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
        - noble
  galaxy_tags:
    - user
    - ssh
    - sudo
    - ubuntu
dependencies: []
